/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package knowledgeonweb;

import AppPackage.AnimationClass;
import javax.swing.ImageIcon;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JProgressBar;
import javax.swing.Timer;

/**
 *
 * @author Daniel
 */
public class ApplicationForm extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationForm
     */
    
    AnimationClass ac = new AnimationClass();
    public ApplicationForm() {
        initComponents();
        setSize(590,332);
        setLocationRelativeTo(null);
        SlideShow();
    }

    public void SlideShow(){
        
        new Thread(){
            int count;
            
            @Override
            public void run(){
                try{
                    while(true){
                        switch(count){
                            case 0:
                                
                                ImageIcon img1 = new ImageIcon(getClass().getResource("/resized/slider_1.jpg"));
                                jLabel1.setIcon(img1);
                                
                                Thread.sleep(3000);
                                
                                ac.jLabelXLeft(0, -590, 20, 5, jLabel1);
                                ac.jLabelXLeft(590, 0, 20, 5, jLabel2);
                                
                                count = 1;
                                break;
                                
                            case 1:
                                
                                ImageIcon img2 = new ImageIcon(getClass().getResource("/resized/slider_2.jpg"));
                                jLabel2.setIcon(img2);
                                
                                Thread.sleep(3000);
                                
                                ac.jLabelXRight(-590, 0, 20, 5, jLabel1);
                                ac.jLabelXRight(0, 590, 20, 5, jLabel2);

                                count = 2;
                                break;
                                
                            case 2:

                                ImageIcon img3 = new ImageIcon(getClass().getResource("/resized/slider-3.jpg"));
                                jLabel1.setIcon(img3);
                                
                                Thread.sleep(3000);
                                
                                ac.jLabelXLeft(0, -590, 20, 5, jLabel1);
                                ac.jLabelXLeft(590, 0, 20, 5, jLabel2);

                                count = 3;
                                break;
                                
                            case 3:

                                ImageIcon img4 = new ImageIcon(getClass().getResource("/resized/slider_4.jpg"));
                                jLabel2.setIcon(img4);
                                
                                Thread.sleep(3000);
                                ac.jLabelXRight(-590, 0, 20, 5, jLabel1);
                                ac.jLabelXRight(0, 590, 20, 5, jLabel2);

                                count = 4;
                                break;
                                
                            case 4:

                                ImageIcon img5 = new ImageIcon(getClass().getResource("/resized/slider_5.jpg"));
                                jLabel1.setIcon(img5);
                                
                                Thread.sleep(3000);
                                ac.jLabelXLeft(0, -590, 20, 5, jLabel1);
                                ac.jLabelXLeft(590, 0, 20, 5, jLabel2);

                                count = 5;
                                break;
                                
                            case 5:

                                ImageIcon img6 = new ImageIcon(getClass().getResource("/resized/slider_6.jpg"));
                                jLabel2.setIcon(img6);
                                
                                Thread.sleep(3000);
                                ac.jLabelXRight(-590, 0, 20, 5, jLabel1);
                                ac.jLabelXRight(0, 590, 20, 5, jLabel2);

                                count = 0;
                                break;
                        }
                    }
                }catch(Exception e){
                    
                }
            }
        }.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        progressBarPanel = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setPreferredSize(new java.awt.Dimension(590, 332));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 320);

        jLabel2.setPreferredSize(new java.awt.Dimension(590, 332));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(590, 0, 590, 332);

        progressBarPanel.setBackground(new java.awt.Color(153, 0, 0));
        progressBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setBackground(new java.awt.Color(204, 102, 0));
        jProgressBar1.setForeground(new java.awt.Color(0, 0, 204));
        jProgressBar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jProgressBar1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        progressBarPanel.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 20));

        getContentPane().add(progressBarPanel);
        progressBarPanel.setBounds(0, 340, 600, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jProgressBar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jProgressBar1AncestorAdded
        // TODO add your handling code here:
        Timer timer = new Timer(100, new ActionListener() {
            int i = 0;

            public void actionPerformed(ActionEvent evt) {
                jProgressBar1.setValue(i);
                i++;
                progressBarPanel.repaint();
                if (i == 100) {
                    ((Timer) evt.getSource()).stop();
                    dispose();
                    new LoginForm().setVisible(true);
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_jProgressBar1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPanel progressBarPanel;
    // End of variables declaration//GEN-END:variables
}
