	/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package knowledgeonweb;

import java.awt.Color;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;
import knowledgeonweb.MenuForm;

/**
 *
 * @author Daniel
 */
public class GraduateSchoolsForm extends javax.swing.JFrame {

    /**
     * Creates new form GraduateSchoolsForm
     */
    int xx, xy;
    
  
    public GraduateSchoolsForm() {
        initComponents();
        setSize(1300, 700);
        setLocationRelativeTo(null);
        readDB();
        
        URL url = getClass().getResource("/kw/logoTrans.png");
        ImageIcon imgicon = new ImageIcon(url);
        super.setIconImage(imgicon.getImage());
    }

    void readDB() {
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:KnowledgeOnWebDB.db");
            Statement stat = conn.createStatement();
            String sqlselect = "select schoolCode, schoolName, contactName, contactPhone,"
                    + "email, programName, noOfSemesters, curriculum, prerequisites from GraduateSchoolsData";
            PreparedStatement pst = conn.prepareStatement(sqlselect);
            ResultSet rs = pst.executeQuery();
            gradSchoolTable.setModel(DbUtils.resultSetToTableModel(rs));
            TableColumnModel tcm = gradSchoolTable.getColumnModel();
            tcm.getColumn(0).setHeaderValue("School code");
            tcm.getColumn(1).setHeaderValue("School name");
            tcm.getColumn(2).setHeaderValue("Contact person");
            tcm.getColumn(3).setHeaderValue("Contact phone");
            tcm.getColumn(4).setHeaderValue("E-Mail");
            tcm.getColumn(5).setHeaderValue("Program name");
            tcm.getColumn(6).setHeaderValue("No of semesters");
            tcm.getColumn(7).setHeaderValue("Curriculum");
            tcm.getColumn(8).setHeaderValue("Pre-requisites");

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mainpanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        GradSchoolformexit = new javax.swing.JLabel();
        GradSchoolminimise = new javax.swing.JLabel();
        editPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        updategradTable = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addgradrecord = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        deletegradrecord = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        warningtext = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        warningicon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradSchoolTable = new javax.swing.JTable();
        GOTOmenuAppform = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        GOTOstd = new javax.swing.JLabel();
        getcode = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        getschoolname = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        getContactname = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        getphone = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        getprogram = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        getsemesters = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        clearfields = new javax.swing.JLabel();
        getemail = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Mainpanel.setBackground(new java.awt.Color(255, 255, 255));
        Mainpanel.setToolTipText("");
        Mainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(255, 0, 0));
        headerPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerPanelMouseDragged(evt);
            }
        });
        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerPanelMousePressed(evt);
            }
        });

        GradSchoolformexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit1_32.png"))); // NOI18N
        GradSchoolformexit.setAutoscrolls(true);
        GradSchoolformexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GradSchoolformexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GradSchoolformexitMouseClicked(evt);
            }
        });

        GradSchoolminimise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png_32.png"))); // NOI18N
        GradSchoolminimise.setAutoscrolls(true);
        GradSchoolminimise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GradSchoolminimise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GradSchoolminimiseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(1216, Short.MAX_VALUE)
                .addComponent(GradSchoolminimise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GradSchoolformexit)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GradSchoolformexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GradSchoolminimise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Mainpanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 40));

        editPanel.setBackground(new java.awt.Color(255, 0, 0));
        editPanel.setForeground(new java.awt.Color(255, 255, 255));
        editPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        updategradTable.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        updategradTable.setForeground(new java.awt.Color(255, 255, 255));
        updategradTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update_32.png"))); // NOI18N
        updategradTable.setText("  Update");
        updategradTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updategradTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updategradTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updategradTableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updategradTableMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updategradTable, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updategradTable, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        editPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 40));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        addgradrecord.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        addgradrecord.setForeground(new java.awt.Color(255, 255, 255));
        addgradrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_into_32.png"))); // NOI18N
        addgradrecord.setText("   Add");
        addgradrecord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addgradrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addgradrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addgradrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addgradrecordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addgradrecord, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addgradrecord, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        editPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 40));

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));

        deletegradrecord.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        deletegradrecord.setForeground(new java.awt.Color(255, 255, 255));
        deletegradrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_32.png"))); // NOI18N
        deletegradrecord.setText("  Delete");
        deletegradrecord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletegradrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletegradrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletegradrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletegradrecordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deletegradrecord, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deletegradrecord, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        editPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 170, 40));

        jPanel6.setBackground(new java.awt.Color(255, 0, 0));
        jPanel6.setForeground(new java.awt.Color(255, 204, 51));

        warningtext.setForeground(new java.awt.Color(255, 255, 51));
        warningtext.setName("warningtext"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(warningtext, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(warningtext, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        editPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 170, 30));

        jPanel7.setBackground(new java.awt.Color(255, 0, 0));
        jPanel7.setForeground(new java.awt.Color(255, 204, 51));

        warningicon.setForeground(new java.awt.Color(255, 255, 51));
        warningicon.setName("warninglabel"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(warningicon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(warningicon, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        editPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 170, 30));

        Mainpanel.add(editPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, 660));

        gradSchoolTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "School code", "School name", "Contatc name", "Contact phone", "E-mail", "Program name", "No of semesters", "Curriculum", "Pre-requisites"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradSchoolTable.setRowHeight(20);
        gradSchoolTable.setSelectionBackground(new java.awt.Color(255, 0, 0));
        gradSchoolTable.getTableHeader().setResizingAllowed(false);
        gradSchoolTable.getTableHeader().setReorderingAllowed(false);
        gradSchoolTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradSchoolTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradSchoolTable);

        Mainpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 1120, 500));

        GOTOmenuAppform.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GOTOmenuAppform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view_32.png"))); // NOI18N
        GOTOmenuAppform.setText("Menu/Application Form");
        GOTOmenuAppform.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GOTOmenuAppform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GOTOmenuAppformMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GOTOmenuAppformMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GOTOmenuAppformMouseExited(evt);
            }
        });
        Mainpanel.add(GOTOmenuAppform, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 200, 40));
        Mainpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 160, 10));
        Mainpanel.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 120, 10));

        GOTOstd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GOTOstd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view_32.png"))); // NOI18N
        GOTOstd.setText("Students' Details");
        GOTOstd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GOTOstd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GOTOstdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GOTOstdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GOTOstdMouseExited(evt);
            }
        });
        Mainpanel.add(GOTOstd, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 170, 40));

        getcode.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        getcode.setText("CODE");
        getcode.setBorder(null);
        Mainpanel.add(getcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 230, 30));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        Mainpanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 230, 10));

        getschoolname.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        getschoolname.setText("SCHOOL");
        getschoolname.setBorder(null);
        Mainpanel.add(getschoolname, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, 280, 30));

        jSeparator10.setBackground(new java.awt.Color(102, 102, 102));
        Mainpanel.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 280, 10));

        getContactname.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        getContactname.setText("CONTACT");
        getContactname.setBorder(null);
        Mainpanel.add(getContactname, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, 250, 30));

        jSeparator11.setBackground(new java.awt.Color(102, 102, 102));
        Mainpanel.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 640, 250, 10));

        getphone.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        getphone.setText("PHONE");
        getphone.setBorder(null);
        Mainpanel.add(getphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 610, 250, 30));

        jSeparator12.setBackground(new java.awt.Color(102, 102, 102));
        Mainpanel.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 640, 250, 10));

        getprogram.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        getprogram.setText("PROGRAM");
        getprogram.setBorder(null);
        Mainpanel.add(getprogram, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 660, 280, 30));

        jSeparator14.setBackground(new java.awt.Color(102, 102, 102));
        Mainpanel.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 690, 280, 10));

        getsemesters.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        getsemesters.setText("SEMESTERS");
        getsemesters.setBorder(null);
        Mainpanel.add(getsemesters, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 660, 130, 30));

        jSeparator15.setBackground(new java.awt.Color(102, 102, 102));
        Mainpanel.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 690, 130, 10));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view_16.png"))); // NOI18N
        jLabel1.setText("GRADUATE SCHOOLS DATA");
        Mainpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 290, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        clearfields.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        clearfields.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear_32.png"))); // NOI18N
        clearfields.setText("Clear Fields");
        clearfields.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearfields.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearfieldsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clearfields, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clearfields, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Mainpanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 660, 100, 50));

        getemail.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        getemail.setText("E-MAIL");
        getemail.setBorder(null);
        Mainpanel.add(getemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, 350, 30));

        jSeparator13.setBackground(new java.awt.Color(102, 102, 102));
        Mainpanel.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 690, 350, 10));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Mainpanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 10, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1302, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GradSchoolformexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GradSchoolformexitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_GradSchoolformexitMouseClicked

    private void GradSchoolminimiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GradSchoolminimiseMouseClicked
        // TODO add your handling code here:
        this.setState(GraduateSchoolsForm.ICONIFIED);
    }//GEN-LAST:event_GradSchoolminimiseMouseClicked

    private void headerPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_headerPanelMouseDragged

    private void headerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_headerPanelMousePressed

    private void addgradrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addgradrecordMouseEntered
        // TODO add your handling code here:
        ImageIcon imgII = new ImageIcon(getClass().getResource("/icons/Add_32.png"));
        jPanel3.setBackground(Color.white);
        addgradrecord.setForeground(Color.red);
        addgradrecord.setIcon(imgII);
    }//GEN-LAST:event_addgradrecordMouseEntered

    private void addgradrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addgradrecordMouseExited
        // TODO add your handling code here:
        ImageIcon imgI = new ImageIcon(getClass().getResource("/icons/add_into_32.png"));
        jPanel3.setBackground(Color.red);
        addgradrecord.setForeground(Color.white);
        addgradrecord.setIcon(imgI);
    }//GEN-LAST:event_addgradrecordMouseExited

    private void updategradTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updategradTableMouseEntered
        // TODO add your handling code here:
        ImageIcon imgIII = new ImageIcon(getClass().getResource("/icons/updte_32.png"));
        jPanel2.setBackground(Color.white);
        updategradTable.setForeground(Color.red);
        updategradTable.setIcon(imgIII);
    }//GEN-LAST:event_updategradTableMouseEntered

    private void updategradTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updategradTableMouseExited
        // TODO add your handling code here:
        ImageIcon imgIV = new ImageIcon(getClass().getResource("/icons/update_32.png"));
        jPanel2.setBackground(Color.red);
        updategradTable.setForeground(Color.white);
        updategradTable.setIcon(imgIV);
    }//GEN-LAST:event_updategradTableMouseExited

    private void deletegradrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletegradrecordMouseEntered
        // TODO add your handling code here:
        ImageIcon imgV = new ImageIcon(getClass().getResource("/icons/trash_32.png"));
        jPanel4.setBackground(Color.white);
        deletegradrecord.setForeground(Color.red);
        deletegradrecord.setIcon(imgV);
    }//GEN-LAST:event_deletegradrecordMouseEntered

    private void deletegradrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletegradrecordMouseExited
        // TODO add your handling code here:
        ImageIcon imgVI = new ImageIcon(getClass().getResource("/icons/delete_32.png"));
        jPanel4.setBackground(Color.red);
        deletegradrecord.setForeground(Color.white);
        deletegradrecord.setIcon(imgVI);
    }//GEN-LAST:event_deletegradrecordMouseExited

    private void GOTOmenuAppformMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOTOmenuAppformMouseEntered
        // TODO add your handling code here:
        ImageIcon img3 = new ImageIcon(getClass().getResource("/icons/arrow2_32.png"));
        GOTOmenuAppform.setForeground(Color.blue);
        GOTOmenuAppform.setIcon(img3);
    }//GEN-LAST:event_GOTOmenuAppformMouseEntered

    private void GOTOmenuAppformMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOTOmenuAppformMouseExited
        // TODO add your handling code here:
        ImageIcon img33 = new ImageIcon(getClass().getResource("/icons/view_32.png"));
        GOTOmenuAppform.setForeground(Color.black);
        GOTOmenuAppform.setIcon(img33);
    }//GEN-LAST:event_GOTOmenuAppformMouseExited

    private void GOTOstdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOTOstdMouseEntered
        // TODO add your handling code here:
        ImageIcon img1 = new ImageIcon(getClass().getResource("/icons/arrow2_32.png"));
        GOTOstd.setForeground(Color.BLUE);
        GOTOstd.setIcon(img1);
    }//GEN-LAST:event_GOTOstdMouseEntered

    private void GOTOstdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOTOstdMouseExited
        // TODO add your handling code here:
        ImageIcon img11 = new ImageIcon(getClass().getResource("/icons/view_32.png"));
        GOTOstd.setForeground(Color.BLACK);
        GOTOstd.setIcon(img11);
    }//GEN-LAST:event_GOTOstdMouseExited

    private void GOTOmenuAppformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOTOmenuAppformMouseClicked
        // TODO add your handling code here:
        dispose();
        new MenuForm().setVisible(true);
    }//GEN-LAST:event_GOTOmenuAppformMouseClicked

    private void gradSchoolTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradSchoolTableMouseClicked
        // TODO add your handling code here:
        int row = gradSchoolTable.getSelectedRow();
        String Table_clicked = (gradSchoolTable.getModel().getValueAt(row, 0).toString());

        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:KnowledgeOnWebDB.db");
            String query = "select * from GraduateSchoolsData where schoolcode = '" + Table_clicked + "' ";
            PreparedStatement pst1 = conn.prepareStatement(query);
            ResultSet rs1 = pst1.executeQuery();

            while (rs1.next()) {
                String add1 = rs1.getString("schoolCode");
                getcode.setText(add1);
                String add2 = rs1.getString("schoolName");
                getschoolname.setText(add2);
                String add3 = rs1.getString("contactName");
                getContactname.setText(add3);
                String add4 = rs1.getString("contactPhone");
                getphone.setText(add4);
                String add5 = rs1.getString("email");
                getemail.setText(add5);
                String add6 = rs1.getString("programName");
                getprogram.setText(add6);
                String add7 = rs1.getString("noOfSemesters");
                getsemesters.setText(add7);

            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_gradSchoolTableMouseClicked

    private void clearfieldsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearfieldsMouseClicked
        // TODO add your handling code here:
        getcode.setText("CODE");
        getschoolname.setText("SCHOOL");
        getContactname.setText("CONTACT");
        getphone.setText("PHONE");
        getemail.setText("E-MAIL");
        getprogram.setText("PROGRAM");
        getsemesters.setText("SEMESTERS");
    }//GEN-LAST:event_clearfieldsMouseClicked

    private void updategradTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updategradTableMouseClicked
        // TODO add your handling code here:
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:KnowledgeOnWebDB.db");
            String schoolcode = getcode.getText();
            String schoolname = getschoolname.getText();
            String person = getContactname.getText();
            String phone = getphone.getText();
            String program = getemail.getText();
            String email = getprogram.getText();
            String semesters = getsemesters.getText();
            
            String query1 = "update GraduateSchoolsData set schoolCode='"+schoolcode+"', schoolName ='"+schoolname+"',"
                            + "contactName ='"+person+"', contactPhone='"+phone+"', programName='"+program+"',"
                    + "email='"+email+"', noOfSemesters='"+semesters+"' where schoolCode='"+schoolcode+"' ";
            if(schoolcode.equalsIgnoreCase("code") || schoolname.equalsIgnoreCase("school") || person.equalsIgnoreCase("contact") || phone.equalsIgnoreCase("phone")
                    || program.equalsIgnoreCase("program") || semesters.equalsIgnoreCase("semesters")){
                
            }else if(schoolcode.isEmpty() && schoolname.isEmpty() && person.isEmpty() && person.isEmpty() && phone.isEmpty() && program.isEmpty() && email.isEmpty()
                    && semesters.isEmpty())
            {
                ImageIcon imgO = new ImageIcon(getClass().getResource("/icons/Attention_32.png"));
                warningicon.setIcon(imgO);
                warningtext.setText("  Seems all fields are empty!");
            }else{
                ImageIcon imgO1 = new ImageIcon(getClass().getResource("/icons/okay_32.png"));
                warningicon.setIcon(imgO1);
                warningtext.setText("       Details Updated!!");
                PreparedStatement pst2 = conn.prepareStatement(query1);
                pst2=conn.prepareStatement(query1);
                pst2.execute();
//                
//                warningicon.setIcon(null);
//                warningtext.setText(null);
                
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        readDB();
    }//GEN-LAST:event_updategradTableMouseClicked

    private void deletegradrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletegradrecordMouseClicked
        // TODO add your handling code here:
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:KnowledgeOnWebDB.db");
            
            
            if(getcode.getText().equalsIgnoreCase("code") || getschoolname.getText().equalsIgnoreCase("school") || getContactname.getText().equalsIgnoreCase("contact") 
                    || getphone.getText().equalsIgnoreCase("phone") || getemail.getText().equalsIgnoreCase("e-mail") || getprogram.getText().equalsIgnoreCase("program") || getsemesters.getText().equalsIgnoreCase("semesters"))
            {
                ImageIcon img33 = new ImageIcon(getClass().getResource("/icons/Neutral_32.png"));
                warningicon.setIcon(img33);
                warningtext.setText("       no data to delete ");
            }else{
                int option = JOptionPane.showConfirmDialog(null, "You want to delete record?","Delete",JOptionPane.YES_NO_OPTION);
                if(option == 0){

                    String query2 = "delete from GraduateSchoolsData where schoolCode = ?";
                    PreparedStatement pst2 = conn.prepareStatement(query2);
                    pst2.setString(1, getcode.getText());

                    pst2.execute();
                    ImageIcon img2 = new ImageIcon(getClass().getResource("/icons/dispose_32.png"));
                    warningicon.setIcon(img2);
                    warningtext.setText("       Delete Successfull!!");

                }else{
                    
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        readDB();
        clearfieldsMouseClicked(evt);
    }//GEN-LAST:event_deletegradrecordMouseClicked

    private void addgradrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addgradrecordMouseClicked
        // TODO add your handling code here:
         try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:KnowledgeOnWebDB.db");
            
            String query3 = "Insert into GraduateSchoolsData (schoolCode, schoolName, contactName, contactPhone, email, programName, noOfSemesters) "
                    + "values (?,?,?,?,?,?,?)";
            PreparedStatement pst3=conn.prepareStatement(query3);
            pst3.setString(1, getcode.getText());
            pst3.setString(2, getschoolname.getText());
            pst3.setString(3, getContactname.getText());
            pst3.setString(4, getphone.getText());
            pst3.setString(5, getemail.getText());
            pst3.setString(6, getprogram.getText());
            pst3.setString(7, getsemesters.getText());
            
            if(getcode.getText().isEmpty() && getschoolname.getText().isEmpty() && getContactname.getText().isEmpty() 
                && getphone.getText().isEmpty() && getemail.getText().isEmpty() && getprogram.getText().isEmpty() && getsemesters.getText().isEmpty())
            {
                ImageIcon img31 = new ImageIcon(getClass().getResource("/icons/Sad_32.png"));
                warningicon.setIcon(img31);
                warningtext.setText("       All fields are empty");
                
            }else if(getcode.getText().isEmpty() || getschoolname.getText().isEmpty() || getContactname.getText().isEmpty() 
                || getphone.getText().isEmpty() || getemail.getText().isEmpty() || getprogram.getText().isEmpty() || getsemesters.getText().isEmpty())
            {
                ImageIcon img33 = new ImageIcon(getClass().getResource("/icons/Neutral_32.png"));
                warningicon.setIcon(img33);
                warningtext.setText("       Some fields are empty");
                
            }else if(getcode.getText().equalsIgnoreCase("code") || getschoolname.getText().equalsIgnoreCase("school") || getContactname.getText().equalsIgnoreCase("contact") 
                    || getphone.getText().equalsIgnoreCase("phone") || getemail.getText().equalsIgnoreCase("e-mail") || getprogram.getText().equalsIgnoreCase("program") || getsemesters.getText().equalsIgnoreCase("semesters"))
            {
                warningtext.setText("       data not inserted");
            }else {
                ImageIcon img34 = new ImageIcon(getClass().getResource("/icons/Happy_32.png"));
                warningicon.setIcon(img34);
                warningtext.setText("       Saved Successfully");
                pst3.execute();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
        readDB();
    }//GEN-LAST:event_addgradrecordMouseClicked

    private void GOTOstdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOTOstdMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new StudentDetailsForm().setVisible(true);
    }//GEN-LAST:event_GOTOstdMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GraduateSchoolsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GraduateSchoolsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GraduateSchoolsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GraduateSchoolsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GraduateSchoolsForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GOTOmenuAppform;
    private javax.swing.JLabel GOTOstd;
    private javax.swing.JLabel GradSchoolformexit;
    private javax.swing.JLabel GradSchoolminimise;
    private javax.swing.JPanel Mainpanel;
    private javax.swing.JLabel addgradrecord;
    private javax.swing.JLabel clearfields;
    private javax.swing.JLabel deletegradrecord;
    private javax.swing.JPanel editPanel;
    private javax.swing.JTextField getContactname;
    private javax.swing.JTextField getcode;
    private javax.swing.JTextField getemail;
    private javax.swing.JTextField getphone;
    private javax.swing.JTextField getprogram;
    private javax.swing.JTextField getschoolname;
    private javax.swing.JTextField getsemesters;
    private javax.swing.JTable gradSchoolTable;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel updategradTable;
    private javax.swing.JLabel warningicon;
    private javax.swing.JLabel warningtext;
    // End of variables declaration//GEN-END:variables
}
