/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package knowledgeonweb;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    
    int xy;
    int xx;
    
    String username, password;

    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null);
        createNewTable();
        
        URL url = getClass().getResource("/kw/logoTrans.png");
        ImageIcon imgicon = new ImageIcon(url);
        super.setIconImage(imgicon.getImage());
    }

    public void createNewTable(){
        // SQLite connection string
        try{
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:KnowledgeOnWebDB.db");
            Statement stat = conn.createStatement();
            stat.executeUpdate("DROP TABLE IF EXISTS AdminLoginData;");
            stat.executeUpdate("CREATE TABLE AdminLoginData (accessusername, accesspassword);");
            PreparedStatement prep = conn.prepareStatement("INSERT INTO AdminLoginData VALUES (?, ?);");
            prep.setString(1, "controlaccess222");
            prep.setString(2, "microsoft");
            prep.addBatch();
            conn.setAutoCommit(false);
            prep.executeBatch();
            conn.setAutoCommit(true);
            ResultSet rs = stat.executeQuery("SELECT * FROM AdminLoginData;");
            while (rs.next()) {
                username = rs.getString("accessusername");
                password = rs.getString("accesspassword");
                //System.out.print("Username = " + username + " ");
                //System.out.println("Password = " + password);
            }
            rs.close();
            conn.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        fieldpword = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        fielduname1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lbluname = new javax.swing.JLabel();
        lblpword = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelminimiselogin = new javax.swing.JPanel();
        minimiselogin = new javax.swing.JLabel();
        panelexitlogin = new javax.swing.JPanel();
        exitlogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 10));

        fieldpword.setBackground(new java.awt.Color(0, 0, 0));
        fieldpword.setForeground(Color.gray);
        fieldpword.setText("Password");
        fieldpword.setBorder(null);
        fieldpword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldpwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldpwordFocusLost(evt);
            }
        });
        fieldpword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldpwordActionPerformed(evt);
            }
        });
        fieldpword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldpwordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldpwordKeyTyped(evt);
            }
        });
        jPanel3.add(fieldpword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 330, 20));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 330, 20));

        fielduname1.setBackground(new java.awt.Color(0, 0, 0));
        fielduname1.setForeground(new java.awt.Color(255, 255, 255));
        fielduname1.setText("Username");
        fielduname1.setBorder(null);
        fielduname1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fielduname1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fielduname1FocusLost(evt);
            }
        });
        fielduname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fielduname1KeyTyped(evt);
            }
        });
        jPanel3.add(fielduname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 330, 20));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 330, 20));

        lbluname.setBackground(new java.awt.Color(0, 0, 0));
        lbluname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbluname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 130, 20));

        lblpword.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblpword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 130, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 810, 340));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/adminavatar.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/coollogo_com-191601050.png"))); // NOI18N
        jLabel4.setText("        ");
        jLabel4.setPreferredSize(new java.awt.Dimension(259, 64));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        panelminimiselogin.setBackground(new java.awt.Color(255, 255, 255));
        panelminimiselogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimiselogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/min.png"))); // NOI18N
        minimiselogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimiselogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimiseloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimiseloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimiseloginMouseExited(evt);
            }
        });
        panelminimiselogin.add(minimiselogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 60, 30));

        jPanel2.add(panelminimiselogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 60, 50));

        panelexitlogin.setBackground(new java.awt.Color(255, 255, 255));

        exitlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Shutdown.png"))); // NOI18N
        exitlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitloginMouseExited(evt);
            }
        });
        panelexitlogin.add(exitlogin);

        jPanel2.add(panelexitlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 60, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitloginMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitloginMouseClicked

    private void minimiseloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimiseloginMouseClicked
        // TODO add your handling code here:
        this.setState(LoginForm.ICONIFIED);
    }//GEN-LAST:event_minimiseloginMouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void fielduname1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fielduname1FocusGained
        // TODO add your handling code here:
        if(fielduname1.getText().equals("Username")){
            fielduname1.setText("");
            lbluname.setText("Username");
            lbluname.setForeground(Color.gray);
        }
        if(!fielduname1.getText().equals("Username")){
            fielduname1.setForeground(Color.white);
        }
    }//GEN-LAST:event_fielduname1FocusGained

    private void fielduname1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fielduname1FocusLost
        // TODO add your handling code here:
        if(!fielduname1.getText().isEmpty()){
            
        }else{
            fielduname1.setText("Username");
            fielduname1.setForeground(Color.gray);
            lbluname.setText("");
        }
        if(!fielduname1.getText().equals("Username")){
            fielduname1.setForeground(Color.white);
        }
    }//GEN-LAST:event_fielduname1FocusLost

    private void fielduname1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fielduname1KeyTyped
        // TODO add your handling code here:
        if(fielduname1.getText().length()== 20){
            evt.consume();
        }
    }//GEN-LAST:event_fielduname1KeyTyped

    private void exitloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitloginMouseEntered
        // TODO add your handling code here:
        panelexitlogin.setBackground(Color.gray);
    }//GEN-LAST:event_exitloginMouseEntered

    private void minimiseloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimiseloginMouseEntered
        // TODO add your handling code here:
        panelminimiselogin.setBackground(Color.gray);
    }//GEN-LAST:event_minimiseloginMouseEntered

    private void exitloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitloginMouseExited
        // TODO add your handling code here:
         panelexitlogin.setBackground(Color.white);
    }//GEN-LAST:event_exitloginMouseExited

    private void minimiseloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimiseloginMouseExited
        // TODO add your handling code here:
        panelminimiselogin.setBackground(Color.white);
    }//GEN-LAST:event_minimiseloginMouseExited

    private void fieldpwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldpwordKeyTyped
        // TODO add your handling code here:
        if(fieldpword.getText().length()== 20){
            evt.consume();
        }
    }//GEN-LAST:event_fieldpwordKeyTyped

    private void fieldpwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldpwordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!fielduname1.getText().equals(username) || !fieldpword.getText().equals(password)){
                JOptionPane.showMessageDialog(null, "ACCESS DENIED\ncheck entry details");

            }else{
                JOptionPane.showMessageDialog(null, "ACCESS GRANTED");
                dispose();
                new MenuForm().setVisible(true);
            }
        }

    }//GEN-LAST:event_fieldpwordKeyPressed

    private void fieldpwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldpwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldpwordActionPerformed

    private void fieldpwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldpwordFocusLost
        // TODO add your handling code here:
        if(!fieldpword.getText().isEmpty()){

        }else{
            fieldpword.setText("Password");
            fieldpword.setForeground(Color.gray);
            lblpword.setText("");
        }
        if(!fieldpword.getText().equals("Password")){
            fieldpword.setForeground(Color.white);
        }
    }//GEN-LAST:event_fieldpwordFocusLost

    private void fieldpwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldpwordFocusGained
        // TODO add your handling code here:
        if(fieldpword.getText().equals("Password")){
            fieldpword.setText("");
            lblpword.setText("Password");
            lblpword.setForeground(Color.gray);
        }
        if(!fieldpword.getText().equals("Password")){
            fieldpword.setForeground(Color.white);
        }
    }//GEN-LAST:event_fieldpwordFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitlogin;
    private javax.swing.JTextField fieldpword;
    private javax.swing.JTextField fielduname1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblpword;
    private javax.swing.JLabel lbluname;
    private javax.swing.JLabel minimiselogin;
    private javax.swing.JPanel panelexitlogin;
    private javax.swing.JPanel panelminimiselogin;
    // End of variables declaration//GEN-END:variables
}
