/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package knowledgeonweb;

import java.awt.Color;
import java.awt.HeadlessException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Daniel
 */
public class StudentDetailsForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentDetailsForm
     */
    
    int xx, xy;
    public StudentDetailsForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        readDB();
        
        URL url = getClass().getResource("/kw/logoTrans.png");
        ImageIcon imgicon = new ImageIcon(url);
        super.setIconImage(imgicon.getImage());
    }

    void readDB(){
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:KnowledgeOnWebDB.db");
            Statement stat = conn.createStatement();
            String sqlselect = "select studentname, country, resphone, email, gender, dob, schoolapplied, programappplied from StudentsData";
            PreparedStatement pst = conn.prepareStatement(sqlselect);
            ResultSet rs = pst.executeQuery();
            StudentTable.setModel(DbUtils.resultSetToTableModel(rs));
            TableColumnModel tcm = StudentTable.getColumnModel();
            tcm.getColumn(0).setHeaderValue("Name");
            tcm.getColumn(1).setHeaderValue("Country");
            tcm.getColumn(2).setHeaderValue("Phone");
            tcm.getColumn(3).setHeaderValue("E-Mail");
            tcm.getColumn(4).setHeaderValue("Gender");
            tcm.getColumn(5).setHeaderValue("Date of Birth");
            tcm.getColumn(6).setHeaderValue("School Applied");
            tcm.getColumn(7).setHeaderValue("Program Applied");

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mainpanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        stuDeetslformexit = new javax.swing.JLabel();
        stuDeetsminimise = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        GOTOmenuAppform = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        GOTOstd = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        editPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        deletegradrecord = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        warningtext = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        warningicon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        getname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Mainpanel.setBackground(new java.awt.Color(255, 255, 255));

        headerPanel.setBackground(new java.awt.Color(255, 0, 0));
        headerPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerPanelMouseDragged(evt);
            }
        });
        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerPanelMousePressed(evt);
            }
        });

        stuDeetslformexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit1_32.png"))); // NOI18N
        stuDeetslformexit.setAutoscrolls(true);
        stuDeetslformexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stuDeetslformexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stuDeetslformexitMouseClicked(evt);
            }
        });

        stuDeetsminimise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png_32.png"))); // NOI18N
        stuDeetsminimise.setAutoscrolls(true);
        stuDeetsminimise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stuDeetsminimise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stuDeetsminimiseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(1222, Short.MAX_VALUE)
                .addComponent(stuDeetsminimise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stuDeetslformexit)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stuDeetslformexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stuDeetsminimise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view_16.png"))); // NOI18N
        jLabel1.setText("STUDENTS DATA");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        GOTOmenuAppform.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GOTOmenuAppform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view_32.png"))); // NOI18N
        GOTOmenuAppform.setText("Menu/Application Form");
        GOTOmenuAppform.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GOTOmenuAppform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GOTOmenuAppformMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GOTOmenuAppformMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GOTOmenuAppformMouseExited(evt);
            }
        });

        GOTOstd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GOTOstd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view_32.png"))); // NOI18N
        GOTOstd.setText("Graduate Schools Data");
        GOTOstd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GOTOstd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GOTOstdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GOTOstdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GOTOstdMouseExited(evt);
            }
        });

        editPanel.setBackground(new java.awt.Color(255, 0, 0));
        editPanel.setForeground(new java.awt.Color(255, 255, 255));
        editPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));

        deletegradrecord.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        deletegradrecord.setForeground(new java.awt.Color(255, 255, 255));
        deletegradrecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_32.png"))); // NOI18N
        deletegradrecord.setText("  Delete");
        deletegradrecord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletegradrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletegradrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletegradrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletegradrecordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(deletegradrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deletegradrecord, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        editPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 40));

        jPanel6.setBackground(new java.awt.Color(255, 0, 0));
        jPanel6.setForeground(new java.awt.Color(255, 204, 51));

        warningtext.setForeground(new java.awt.Color(255, 255, 51));
        warningtext.setName("warningtext"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(warningtext, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(warningtext, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        editPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 170, 30));

        jPanel7.setBackground(new java.awt.Color(255, 0, 0));
        jPanel7.setForeground(new java.awt.Color(255, 204, 51));

        warningicon.setForeground(new java.awt.Color(255, 255, 51));
        warningicon.setName("warninglabel"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(warningicon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(warningicon, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        editPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 170, 30));

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Country", "Phone", "E-Mail", "Gender", "Date of birth", "School Applied", "Program"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentTable.setRowHeight(20);
        StudentTable.setSelectionBackground(new java.awt.Color(255, 0, 0));
        StudentTable.getTableHeader().setResizingAllowed(false);
        StudentTable.getTableHeader().setReorderingAllowed(false);
        StudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StudentTable);

        getname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getname.setText("NAME");

        javax.swing.GroupLayout MainpanelLayout = new javax.swing.GroupLayout(Mainpanel);
        Mainpanel.setLayout(MainpanelLayout);
        MainpanelLayout.setHorizontalGroup(
            MainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(MainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainpanelLayout.createSequentialGroup()
                        .addComponent(editPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainpanelLayout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(MainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GOTOmenuAppform, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(MainpanelLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(MainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MainpanelLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(GOTOstd, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(MainpanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainpanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(getname, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        MainpanelLayout.setVerticalGroup(
            MainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainpanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainpanelLayout.createSequentialGroup()
                        .addGroup(MainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainpanelLayout.createSequentialGroup()
                                .addGroup(MainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GOTOmenuAppform, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainpanelLayout.createSequentialGroup()
                                .addComponent(GOTOstd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainpanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(getname, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stuDeetslformexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuDeetslformexitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_stuDeetslformexitMouseClicked

    private void stuDeetsminimiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stuDeetsminimiseMouseClicked
        // TODO add your handling code here:
        this.setState(StudentDetailsForm.ICONIFIED);
    }//GEN-LAST:event_stuDeetsminimiseMouseClicked

    private void headerPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_headerPanelMouseDragged

    private void headerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_headerPanelMousePressed

    private void GOTOmenuAppformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOTOmenuAppformMouseClicked
        // TODO add your handling code here:
        dispose();
        new MenuForm().setVisible(true);
    }//GEN-LAST:event_GOTOmenuAppformMouseClicked

    private void GOTOmenuAppformMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOTOmenuAppformMouseEntered
        // TODO add your handling code here:
        ImageIcon img3 = new ImageIcon(getClass().getResource("/icons/arrow2_32.png"));
        GOTOmenuAppform.setForeground(Color.blue);
        GOTOmenuAppform.setIcon(img3);
    }//GEN-LAST:event_GOTOmenuAppformMouseEntered

    private void GOTOmenuAppformMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOTOmenuAppformMouseExited
        // TODO add your handling code here:
        ImageIcon img33 = new ImageIcon(getClass().getResource("/icons/view_32.png"));
        GOTOmenuAppform.setForeground(Color.black);
        GOTOmenuAppform.setIcon(img33);
    }//GEN-LAST:event_GOTOmenuAppformMouseExited

    private void GOTOstdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOTOstdMouseEntered
        // TODO add your handling code here:
        ImageIcon img1 = new ImageIcon(getClass().getResource("/icons/arrow2_32.png"));
        GOTOstd.setForeground(Color.BLUE);
        GOTOstd.setIcon(img1);
    }//GEN-LAST:event_GOTOstdMouseEntered

    private void GOTOstdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOTOstdMouseExited
        // TODO add your handling code here:
        ImageIcon img11 = new ImageIcon(getClass().getResource("/icons/view_32.png"));
        GOTOstd.setForeground(Color.BLACK);
        GOTOstd.setIcon(img11);
    }//GEN-LAST:event_GOTOstdMouseExited

    private void deletegradrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletegradrecordMouseClicked
        // TODO add your handling code here:
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:KnowledgeOnWebDB.db");

                int option = JOptionPane.showConfirmDialog(null, "You want to delete record?","Delete",JOptionPane.YES_NO_OPTION);
                if(option == 0){

                    String query2 = "delete from StudentsData where studentname = ?";
                    PreparedStatement pst2 = conn.prepareStatement(query2);
                    pst2.setString(1, getname.getText());

                    pst2.execute();
                    ImageIcon img2 = new ImageIcon(getClass().getResource("/icons/dispose_32.png"));
                    warningicon.setIcon(img2);
                    warningtext.setText("       Delete Successfull!!");

                }else{

                }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }

        readDB();
    }//GEN-LAST:event_deletegradrecordMouseClicked

    private void deletegradrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletegradrecordMouseEntered
        // TODO add your handling code here:
        ImageIcon imgV = new ImageIcon(getClass().getResource("/icons/trash_32.png"));
        jPanel4.setBackground(Color.white);
        deletegradrecord.setForeground(Color.red);
        deletegradrecord.setIcon(imgV);
    }//GEN-LAST:event_deletegradrecordMouseEntered

    private void deletegradrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletegradrecordMouseExited
        // TODO add your handling code here:
        ImageIcon imgVI = new ImageIcon(getClass().getResource("/icons/delete_32.png"));
        jPanel4.setBackground(Color.red);
        deletegradrecord.setForeground(Color.white);
        deletegradrecord.setIcon(imgVI);
    }//GEN-LAST:event_deletegradrecordMouseExited

    private void StudentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTableMouseClicked
        // TODO add your handling code here:
        int row = StudentTable.getSelectedRow();
        String Table_clicked = (StudentTable.getModel().getValueAt(row, 0).toString());

        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:KnowledgeOnWebDB.db");
            String query = "select * from StudentsData where studentname = '" + Table_clicked + "' ";
            PreparedStatement pst1 = conn.prepareStatement(query);
            ResultSet rs1 = pst1.executeQuery();

            while (rs1.next()) {
                String add1 = rs1.getString("studentname");
                getname.setText(add1);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_StudentTableMouseClicked

    private void GOTOstdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GOTOstdMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new GraduateSchoolsForm().setVisible(true);
    }//GEN-LAST:event_GOTOstdMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StudentDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StudentDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StudentDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StudentDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StudentDetailsForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GOTOmenuAppform;
    private javax.swing.JLabel GOTOstd;
    private javax.swing.JPanel Mainpanel;
    private javax.swing.JTable StudentTable;
    private javax.swing.JLabel deletegradrecord;
    private javax.swing.JPanel editPanel;
    private javax.swing.JTextField getname;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel stuDeetslformexit;
    private javax.swing.JLabel stuDeetsminimise;
    private javax.swing.JLabel warningicon;
    private javax.swing.JLabel warningtext;
    // End of variables declaration//GEN-END:variables
}
